const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const elements = new Map();
const element = id => {
  if (!elements.has(id)) elements.set(id,{value:'',textContent:'',dataset:{},options:[],children:[],addEventListener(){},append(child){this.children.push(child)},add(child){this.options.push(child)},replaceChildren(){this.children=[];this.options=[]}});
  return elements.get(id);
};
const messages = [];
const frame = element('frame');
frame.contentWindow = {workshopCommand: value=>messages.push(JSON.parse(value))};
let listener;
const context = vm.createContext({structuredClone, console, setTimeout(){}, location:{origin:'http://candidate'}, window:{addEventListener:(_kind,fn)=>listener=fn}, document:{getElementById:element,querySelector:()=>frame,querySelectorAll:()=>[],createElement:()=>element(Symbol())},fetch:()=>new Promise(()=>{}), Option: function(name,id){this.value=id;this.textContent=name}, URL,Blob});
vm.runInContext(fs.readFileSync('tools/workshop/workshop.js','utf8'),context);
const evaluate = code => vm.runInContext(code,context);
evaluate("ready=true;chooseEffect('bolt');settings.spell_size=.8;rememberEffect();chooseEffect('regeneration')");
assert.equal(evaluate('settings.spell_size'),1);
evaluate('settings.spell_size=1.4;rememberEffect()');
listener({source:frame.contentWindow,origin:'http://candidate',data:{source:'spellcast-workshop',kind:'state',payload:{id:'bolt',playing:true,time:0,duration:2}}});
if(process.argv.includes('--known-bad-stale-state'))evaluate("activeId='bolt'");
assert.equal(evaluate('activeId'),'regeneration');
evaluate('settings.particle=1.5;rememberEffect()');
const data=JSON.parse(evaluate('JSON.stringify(exportData())'));
assert.equal(data.schema,2);
assert.equal(data.effect,'regeneration');
assert.equal(data.settings.effect_settings.bolt.spell_size,.8);
assert.equal(data.settings.effect_settings.regeneration.particle,1.5);
assert.equal('spell_size' in data.settings,false);
evaluate("chooseEffect('bolt')");
assert.equal(evaluate('settings.spell_size'),.8);
element('reset').onclick();
evaluate("chooseEffect('regeneration')");
assert.equal(evaluate('settings.spell_size'),1);
assert.equal(Object.keys(JSON.parse(evaluate('JSON.stringify(exportData())')).settings.effect_settings).length,0);
console.log('WORKSHOP SETTINGS CHECKS 10 FAILURES 0');
