import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
folder = root / 'builds/spell-gallery'
entries = json.loads((folder / 'catalog.json').read_text())
assert len([e for e in entries if e['group'] == 'Spells']) == 24
for entry in entries:
    assert entry['frames'] and all((folder / f).is_file() for f in entry['frames'])
payload = json.dumps(entries).replace('</', '<\\/')
html = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SpellCast — visual atlas</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#131c18;color:#ece5d3;font:16px system-ui,sans-serif}header{padding:32px 4vw 20px;max-width:1500px;margin:auto}h1{font:600 clamp(28px,4vw,46px) Georgia,serif;margin:0 0 12px}p{line-height:1.5;color:#bac4b8;margin:8px 0}nav{position:sticky;top:0;background:#1d2b24f5;z-index:2;display:flex;gap:10px;padding:14px 4vw;flex-wrap:wrap;border-block:1px solid #405144}button,input{font:inherit}button{background:#293d30;color:#eee7d1;border:1px solid #627159;border-radius:5px;padding:9px 14px;cursor:pointer}button[aria-pressed=true]{background:#d7cfaa;color:#17251b}input[type=search]{background:#111b15;color:white;border:1px solid #627159;border-radius:5px;padding:9px 12px;flex:1;min-width:180px}#count{align-self:center;color:#bdc8bb}main{max-width:1600px;margin:auto;padding:24px 4vw;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}article{background:#203026;border:1px solid #43533e;border-radius:8px;overflow:hidden}article h2{margin:0;font-size:20px}article .meta{padding:15px 18px;display:flex;justify-content:space-between;gap:10px;align-items:center}small{color:#c2ccb8}.preview{display:block;padding:0;border:0;border-radius:0;width:100%;background:#405e36;position:relative}.preview img{width:100%;display:block;image-rendering:pixelated}.caption{padding:10px 18px;color:#bcc7b6;font-size:13px}dialog{width:min(1400px,96vw);max-height:96vh;padding:0;background:#15221a;color:#f4eedf;border:1px solid #93a57d;border-radius:8px}dialog::backdrop{background:#000c}.dialogbar{display:flex;gap:12px;align-items:center;padding:12px 18px;flex-wrap:wrap}.dialogbar h2{margin:0;flex:1;font-size:20px}dialog img{width:100%;display:block;image-rendering:pixelated}dialog input{flex:1;min-width:180px}#empty{display:none;padding:30px}button:focus-visible,input:focus-visible{outline:3px solid #f0d984;outline-offset:3px}@media(max-width:700px){main{grid-template-columns:1fr}header{padding-top:20px}}@media print{nav,.dialogbar,dialog{display:none}main{display:grid;grid-template-columns:1fr 1fr}article{break-inside:avoid}}
</style>
<header><p>SPELLCAST SURVIVORS · DEBUG REFERENCE</p><h1>Spells, particles & scale</h1><p>Every panel includes the same wizard at the same scale. These are captures of the actual game renderer, with the current 1.5× camera and rank-one spells.</p><p>Open a panel for a full-size comparison and scrub its phases. Targets are held still; Firewalk moves the wizard to lay a trail. Particle panels show one configured example of each effect factory. Playback cycles sampled frames, not a continuous recording; timestamps are approximate.</p></header>
<nav aria-label="Gallery controls"><button data-filter="All" aria-pressed="true">All</button><button data-filter="Spells" aria-pressed="false">Spells</button><button data-filter="Particles" aria-pressed="false">Particles</button><input type="search" aria-label="Find spell or effect" placeholder="Find a spell or effect…"><button id="motion" aria-pressed="false">Play samples</button><span id="count"></span></nav><main></main><p id="empty">No matching effects.</p>
<dialog><div class="dialogbar"><h2></h2><button id="close">Close</button></div><img alt=""><div class="dialogbar"><button id="prev">Previous</button><input type="range" min="0" step="1" aria-label="Effect phase"><button id="next">Next</button><span id="phase"></span></div></dialog>
<script>
const entries=__DATA__;let filter='All',query='',playing=false,tick=0,selected=null,index=0;
const main=document.querySelector('main'),dialog=document.querySelector('dialog'),slider=dialog.querySelector('input');
function defaultIndex(e){if(e.group==='Particles')return 1;const t={meteor_shower:1.0,rune_trap:0.85,frost_sigil:1.5,ember_trail:2.0,plague_seed:1.5,soul_bloom:1.5}[e.id]??0.18;return e.times.findIndex(x=>x>=t)}
function phase(e,i){return typeof e.times[i]==='number'?'~'+e.times[i].toFixed(2)+' s':e.times[i]+' phase'}
function render(){main.replaceChildren();const visible=entries.filter(e=>(filter==='All'||e.group===filter)&&`${e.name} ${e.id}`.toLowerCase().includes(query));for(const e of visible){const a=document.createElement('article');a.innerHTML='<div class="meta"><h2></h2><small></small></div><button class="preview"><img loading="lazy"></button><div class="caption"></div>';a.querySelector('h2').textContent=e.name;a.querySelector('small').textContent=e.bonus?'Combination':e.group;a.querySelector('button').setAttribute('aria-label','Inspect '+e.name);const img=a.querySelector('img');img.src=e.frames[defaultIndex(e)];img.alt=e.name+' beside wizard';a.querySelector('.caption').textContent='Same camera scale · '+phase(e,defaultIndex(e))+' · click to inspect';a.querySelector('button').onclick=()=>open(e);a.dataset.id=e.id;main.append(a)}document.querySelector('#count').textContent=visible.length+' / '+entries.length+' effects';document.querySelector('#empty').style.display=visible.length?'none':'block'}
function updateModal(){const img=dialog.querySelector('img');img.src=selected.frames[index];img.alt=selected.name+' — '+phase(selected,index);slider.value=index;document.querySelector('#phase').textContent=phase(selected,index)}
function open(e){playing=false;document.querySelector('#motion').setAttribute('aria-pressed','false');document.querySelector('#motion').textContent='Play samples';selected=e;index=defaultIndex(e);dialog.querySelector('h2').textContent=e.name;slider.max=e.frames.length-1;updateModal();dialog.showModal()}
for(const b of document.querySelectorAll('[data-filter]'))b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));render()};document.querySelector('[type=search]').oninput=e=>{query=e.target.value.toLowerCase();render()};document.querySelector('#close').onclick=()=>dialog.close();slider.oninput=()=>{index=Number(slider.value);updateModal()};document.querySelector('#prev').onclick=()=>{index=(index+selected.frames.length-1)%selected.frames.length;updateModal()};document.querySelector('#next').onclick=()=>{index=(index+1)%selected.frames.length;updateModal()};document.querySelector('#motion').onclick=e=>{playing=!playing;e.target.setAttribute('aria-pressed',playing);e.target.textContent=playing?'Pause samples':'Play samples'};
setInterval(()=>{if(!playing)return;tick++;if(dialog.open){index=(index+1)%selected.frames.length;updateModal();return}for(const a of main.children){const e=entries.find(x=>x.id===a.dataset.id),i=tick%e.frames.length;a.querySelector('img').src=e.frames[i];a.querySelector('.caption').textContent='Same camera scale · '+phase(e,i)+' · click to inspect'}},450);render();
</script></html>'''.replace('__DATA__',payload)
(folder / 'index.html').write_text(html)
print(f'Built gallery: {len(entries)} entries, {sum(len(e["frames"]) for e in entries)} native frames')
